language: ruby

if: branch = travis-deploy

services:
  - 'docker'

before_install:
  - nvm install --lts
  - nvm use --lts
  - gem install jekyll sass bundler jekyll-minifier jekyll-sitemap
  - npm install -g yarn

script:
  - 'make image'

after_success:
  - 'make publish'