# Site settings
name: Mircea Mihalea
title: Mircea Mihalea | Portfolio
description: Software developer, petrolhead and linux enthusiast
url: https://mihalea.ro
baseurl: ""
email: mircea@mihalea.ro
cover: https://mihalea.ro/img/og.png
logo: https://mihalea.ro/img/favicon.png
resume: https://mihalea.ro/resume.pdf
social:
  - title: email
    url: mailto:mircea@mihalea.ro
  - title: github
    url: https://github.com/mihalea
  - title: linkedin
    url: https://www.linkedin.com/in/mihalea-mircea
  - title: instagram
    url: https://instagram.com/mirceamihalea

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
